name: virtue-dev

channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.9
  # Runtime
  - skillbridge = 1.2.18
  # Documentation
  - sphinx = 4.5.0
  - pydata-sphinx-theme = 0.9.0
  - sphinx-panels = 0.6.0
  - sphinx-copybutton = 0.5.0
  - sphinx-autobuild = 2021.3.14
  - sphinx-github-changelog = 1.2.0
  - esbonio = 0.13.1
