name: virtue-dev

channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.9
  - conda
  - conda-build
  - conda-verify
  - mamba
  - boa
# Optional Runtime
  - skillbridge = 1.2.18
# Build
  - flit = 3.7.1
  - pip = 22.2.2
 # Documentation
  - sphinx = 4.5.0
  - pydata-sphinx-theme = 0.9.0
  - sphinx-panels = 0.6.0
  - sphinx-copybutton = 0.5.0
  - sphinx-autobuild = 2021.3.14
  - sphinx-github-changelog = 1.2.0
  - esbonio = 0.13.1
  - sphinx-sitemap = 2.2.0