{% set name = "virtue" %}

package:
  name: "{{ name|lower }}"
  #version: "{{ version }}"
  version: "0.2.1" # Need to make a single place for the version #
source:
  - path: ../conda-recipe
    folder: conda-recipe
  - path: ../virtue
    folder: virtue
  - path: ../tests
    folder: tests
  - path: ../README.md
  - path: ../LICENSE
  - path: ../pyproject.toml

build:
  number: 0

requirements:
  host:
    - python {{ python }}
    - pip=22.2.2
    - flit=3.7.1
  run:
    - python

test:
  imports:
    - virtue

about:
  home: http://www.cascode-labs.org/virtue/
  license: MIT
  summary: Cadence Virtuoso SKILL++ framework
  dev_url: https://github.com/cascode-labs/virtue
  doc_url: http://www.cascode-labs.org/virtue/
  doc_source_url: https://github.com/cascode-labs/virtue/tree/main/docs/source
