name: virtue-dev
channels:
  - conda-forge
  - http://idshost/conda-channels/ids-skyworks/
  - defaults
dependencies:
  - python = 3.7
  - skillbridge
  # - viper # Make editable using pip install --no-deps -e /path/to/viper_repo
  # docs
  - sphinx=4
  - myst-parser=0.18
  - sphinx-panels=0.6
  - sphinx-autobuild=0.7
  - sphinx-copybutton=0.5
  - sphinx_rtd_theme=1.0
